version: 1.0
jobs:
  build:
    steps:
      - run:
          name: Tests
          command: |
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py runserver
#            tests cmd
      - run:
          name: Building
          command: |
            docker-compose up -d
#      - run:
#          name: Publishing
#          command: |
#            heroku