version: 1.0
jobs:
  build:
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Building
          command: |
            docker-compose up -d
  tests:
    steps:
      - run:
          name: Tests
          command: |
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py runserver
#            tests cmd
#  deploy:
#    steps:
#      - run:
#          name: Publishing
#          command: |
#            heroku