version: 1.0
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
      - image: alpine:3.15
      - image: python:3.9-slim

#    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command:
#            apk add --no-cache \
#              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Building
          command: docker-compose up -d
  tests:
    steps:
      - run:
          name: Tests
          command: python manage.py test
#  deploy:
#    steps:
#      - run:
#          name: Publishing
#          command: |
#            heroku