version: 2.1
orbs:
  heroku: circleci/heroku@2.0.0
jobs:
  # 24.0.6
  build:
    docker:
      - image: docker:24.0.6-git
      - image: alpine:3.15
      - image: python:3.9-slim
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update
            apk add nodejs npm
            apk add curl curl-dev bash
            apk add --no-cache py3-pip
            pip install docker-compose==1.12.0 awscli==1.11.76
      - run:
          name: Tests
          command: |
            pip3 install -r requirements.txt
            python manage.py test
            flake8
      - when:
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Building
                command: |
                  docker-compose up -d
            - run:
                name: Docker Login
                command: |
                  docker login -u $DOCKER_USERNAME -p $DOCKER_LOGIN
            - run:
                name: Docker Hub Push
                command: |
                  docker image ls
                  docker image tag project-web:latest ekmah/project-web:latest
                  docker push ekmah/project-web:latest
            - heroku/install
            - run:
                name: Heroku login
                command: |
                  heroku container:login
            - run:
                name: Pushing to Registry
                command: |
                  docker tag project-web registry.heroku.com/p13-open-classrooms/web
                  docker push registry.heroku.com/p13-open-classrooms/web
            - run:
                name: Heroku release
                command: |
                  heroku container:release web -a p13-open-classrooms