version: 1.0
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
      - image: alpine:3.15
      - image: python:3.9-slim
#    resource_class: large
    steps:
#      - setup_remote_docker:
#          version: 20.10.14
      - run:
          name: Building
          command: docker-compose up -d
  tests:
    steps:
      - run:
          name: Tests
          command: python manage.py test
#  deploy:
#    steps:
#      - run:
#          name: Publishing
#          command: |
#            heroku