version: 1.0
jobs:
  # 24.0.6
  build:
    docker:
      - image: docker:24.0.6-git
      - image: alpine:3.15
      - image: python:3.9-slim

#    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py3-pip
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Building
          command: docker-compose up -d
      - run:
          name: Tests
          command: |
            pip3 install -r requirements.txt
            python manage.py test
#  deploy:
#    steps:
#      - run:
#          name: Publishing
#          command: |
#            heroku